import { categorys } from './categorys';
import { sizelist } from './sizelist';

import Inter_er_Santa_Barbara_1 from '../images/collections/ceramic/Inter_er_Santa_Barbara_1.jpg';
import adagioint from '../images/collections/ceramic/adagioint.jpg';
import djazintgl1 from '../images/collections/ceramic/djazintgl1.jpg';
import kanariint from '../images/collections/ceramic/kanariint.jpg';
import largoint from '../images/collections/ceramic/largoint.jpg';
import sagaint from '../images/collections/ceramic/sagaint.jpg';
import andoraint4 from '../images/collections/ceramic/andoraint4.jpg';

import amsterdamint from '../images/collections/porcelain-tile/amsterdamint.jpg';
import alicante from '../images/collections/porcelain-tile/alicante.jpg';
import bergenint1 from '../images/collections/porcelain-tile/bergenint1.jpg';
import bonnint from '../images/collections/porcelain-tile/bonnint.jpg';
import budapesht_1 from '../images/collections/porcelain-tile/budapesht_1.jpg';
import medanint from '../images/collections/porcelain-tile/medanint.jpg';
import newyorkint2 from '../images/collections/porcelain-tile/newyorkint2.jpg';

import belmont_tiff from '../images/collections/floor/belmont_tiff.jpg';
import bergenint13 from '../images/collections/floor/bergenint13.jpg';
import dub_olha from '../images/collections/floor/dub_olha.jpg';
import forest_final from '../images/collections/floor/forest_final.jpg';
import katalonia_final from '../images/collections/floor/katalonia_final.jpg';
import loft_wood_olha_nocrop from '../images/collections/floor/loft_wood_olha_nocrop.jpg';
import montrealint2 from '../images/collections/floor/montrealint2.jpg';

import intW101_2_ from '../images/collections/gesso/intW101_2_.jpg';
import intW102 from '../images/collections/gesso/intW102.jpg';
import intW103 from '../images/collections/gesso/intW103.jpg';
import atlasint1 from '../images/collections/gesso/atlasint1.jpg';
import fobosint from '../images/collections/gesso/fobosint.jpg';
import proksima from '../images/collections/gesso/proksima.jpg';
import inter_er from '../images/collections/gesso/inter_er.jpg';

export const initialCollections = [
  {
    top_photo: Inter_er_Santa_Barbara_1,
    name: 'Санта Барбара',
    id: '001',
    price: '754',
    label: 'Новинка',
    categorys: [categorys[0], categorys[4]],
    size: sizelist[0],
    url: 'santa-barbara',
    sale: true,
    surface_type: 'матовая',
  },
  {
    top_photo: adagioint,
    name: 'Адажио',
    id: '002',
    price: '584',
    categorys: [categorys[0]],
    size: sizelist[5],
    url: 'adagio',
    sale: false,
    surface_type: 'матовая',
  },
  {
    top_photo: djazintgl1,
    name: 'Джаз',
    id: '003',
    price: '350',
    label: 'Хит продаж',
    categorys: [categorys[0]],
    size: sizelist[5],
    url: 'djaz',
    sale: false,
    surface_type: 'матовая',
  },
  {
    top_photo: kanariint,
    name: 'Канары',
    id: '004',
    price: '947',
    label: 'Хит продаж',
    categorys: [categorys[0]],
    size: sizelist[0],
    url: 'kanari',
    sale: false,
    surface_type: 'матовая',
  },
  {
    top_photo: largoint,
    name: 'Ларго',
    id: '005',
    price: '457',
    categorys: [categorys[0]],
    size: sizelist[0],
    url: 'largo',
    sale: false,
    surface_type: 'глянцевая',
  },
  {
    top_photo: sagaint,
    name: 'Сага',
    id: '006',
    price: '987',
    categorys: [categorys[0]],
    size: sizelist[5],
    url: 'saga',
    sale: false,
    surface_type: 'матовая',
  },
  {
    top_photo: andoraint4,
    name: 'Андора',
    id: '007',
    price: '568',
    categorys: [categorys[0]],
    size: sizelist[5],
    url: 'andora',
    sale: false,
    surface_type: 'матовая',
  },
  {
    top_photo: amsterdamint,
    id: '008',
    name: 'Amsterdam',
    price: '500',
    label: 'Новинка',
    categorys: [categorys[1]],
    size: sizelist[8],
    url: 'amsterdam',
    sale: false,
    surface_type: 'матовая',
  },
  {
    top_photo: budapesht_1,
    id: '009',
    name: 'Budapest',
    price: '2045',
    label: 'Новинка',
    categorys: [categorys[1], categorys[4]],
    size: sizelist[9],
    url: 'budapesht',
    sale: true,
    surface_type: 'матовая',
  },
  {
    top_photo: medanint,
    id: '010',
    name: 'Medan',
    price: '2190',
    label: 'Новинка',
    categorys: [categorys[1]],
    size: sizelist[8],
    url: 'medan',
    sale: false,
    surface_type: 'глянцевая',
  },
  {
    top_photo: alicante,
    id: '011',
    name: 'Alicante',
    price: '1749',
    categorys: [categorys[1]],
    size: sizelist[6],
    url: 'alicante',
    sale: false,
    surface_type: 'глянцевая',
  },
  {
    top_photo: bergenint1,
    id: '012',
    name: 'Bergen',
    price: '2096',
    categorys: [categorys[1]],
    size: sizelist[9],
    label: 'Новинка',
    url: 'bergen',
    sale: false,
    surface_type: 'матовая',
  },
  {
    top_photo: bonnint,
    id: '013',
    name: 'Bonn',
    price: '1986',
    categorys: [categorys[1], categorys[4]],
    size: sizelist[6],
    label: 'Хит продаж',
    url: 'bonn',
    sale: true,
    surface_type: 'матовая',
  },
  {
    top_photo: newyorkint2,
    id: '014',
    name: 'New York',
    price: '1986',
    categorys: [categorys[1]],
    size: sizelist[6],
    label: 'Новинка',
    url: 'newyork',
    sale: false,
    surface_type: 'матовая',
  },
  {
    top_photo: bergenint13,
    id: '015',
    name: 'Берген',
    price: '929',
    categorys: [categorys[2]],
    size: sizelist[11],
    label: 'Хит продаж',
    url: 'bergenfloor',
    sale: false,
    surface_type: 'матовая',
  },
  {
    top_photo: forest_final,
    id: '016',
    name: 'Форест',
    price: '999',
    categorys: [categorys[2], categorys[4]],
    size: sizelist[10],
    label: 'Хит продаж',
    url: 'forest',
    sale: true,
    surface_type: 'матовая',
  },
  {
    top_photo: montrealint2,
    id: '017',
    name: 'Монреаль',
    price: '999',
    categorys: [categorys[2]],
    size: sizelist[10],
    label: 'Новинка',
    url: 'montreal',
    sale: false,
    surface_type: 'матовая',
  },
  {
    top_photo: dub_olha,
    id: '018',
    name: 'Дублин',
    price: '999',
    categorys: [categorys[2]],
    size: sizelist[10],
    label: 'Хит продаж',
    url: 'dublin',
    sale: false,
    surface_type: 'матовая',
  },
  {
    top_photo: loft_wood_olha_nocrop,
    id: '019',
    name: 'Loft wood',
    price: '929',
    categorys: [categorys[2]],
    size: sizelist[11],
    label: 'Хит продаж',
    url: 'loft_wood',
    sale: false,
    surface_type: 'матовая',
  },
  {
    top_photo: katalonia_final,
    id: '020',
    name: 'Каталония',
    price: '999',
    categorys: [categorys[2], categorys[4]],
    size: sizelist[10],
    label: 'Хит продаж',
    url: 'katalonia',
    sale: true,
    surface_type: 'матовая',
  },
  {
    top_photo: belmont_tiff,
    id: '021',
    name: 'Бельмонт',
    price: '1145',
    categorys: [categorys[2]],
    size: sizelist[10],
    label: 'Новинка',
    url: 'belmont',
    sale: false,
    surface_type: 'матовая',
  },
  {
    top_photo: intW101_2_,
    id: '022',
    name: 'Унитаз-компакт W101',
    price: '6168',
    categorys: [categorys[3]],
    url: 'W101',
    sale: false,
    // label: 'Новинка',
  },
  {
    top_photo: intW102,
    id: '023',
    name: 'Унитаз-компакт W102',
    price: '6168',
    categorys: [categorys[3]],
    url: 'W102',
    sale: false,
    // label: 'Новинка',
  },
  {
    top_photo: intW103,
    id: '024',
    name: 'Унитаз-компакт W103',
    price: '9100',
    categorys: [categorys[3], categorys[4]],
    url: 'W103',
    sale: true,
    // label: 'Новинка',
  },
  {
    top_photo: atlasint1,
    id: '025',
    name: 'Унитаз-компакт АТЛАС',
    price: '8991',
    categorys: [categorys[3]],
    url: 'atlas',
    sale: false,
    // label: 'Новинка',
  },
  {
    top_photo: proksima,
    id: '026',
    name: 'Унитаз-компакт ПРОКСИМА',
    price: '6168',
    categorys: [categorys[3]],
    url: 'proksima',
    sale: false,
    // label: 'Новинка',
  },
  {
    top_photo: fobosint,
    id: '027',
    name: 'Унитаз-компакт ФОБОС',
    price: '8021',
    categorys: [categorys[3]],
    url: 'fobos',
    sale: false,
    // label: 'Новинка',
  },
  {
    top_photo: inter_er,
    id: '028',
    name: 'Унитаз-компакт ЭЛЛАРА',
    price: '8654',
    categorys: [categorys[3]],
    label: 'Новинка',
    url: 'ellara',
    sale: false,
  },
];
